name: I/O
description: I/O, the data nerd blog from the Puget Sound Regional Council
url: http://psrc.github.io
lsi: false
markdown: redcarpet
timezone: America/Los_Angeles
permalink: /:categories/:year/:title
gems:
  - jekyll-sitemap
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

nav_links:
  HOME: '/'
  ABOUT&nbsp;I/O: '/about.html'
  ARCHIVE: '/archive.html'
  MEET&nbsp;THE&nbsp;AUTHORS: '/authors.html'
  PSRC&nbsp;WEBSITE: 'http://www.psrc.org'

psrc_links:
  PSRC Website: "http://www.psrc.org"
  Regional View Blog: "http://blog.psrc.org"
  Contact Us: "http://www.psrc.org/about/contact"

